version: 2.1
orbs:
  android: circleci/android@2.1.2
  flutter: circleci/flutter@1.1.0

jobs:
  android-deployment:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2022.12.1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.10
      - flutter/install_android_gradle
      - flutter/install_android_gem
      - run:
          name: Update flutter
          command: flutter upgrade
      - android/create-avd:
          avd-name: Phone_5.1
          install: true
          system-image: system-images;android-31;default;x86_64
          additional-args: -d 50 # This is a 5.1in WVGA device
      - android/start-emulator:
          avd-name: Phone_5.1
          post-emulator-launch-assemble-command: ''
          restore-gradle-cache-post-emulator-launch: false
      - run:
          name: Fastlane - android deployment
          command: bundle exec fastlane deployment
          working_directory: android
      - android/kill-emulators
      - store_artifacts:
          path: android/fastlane/metadata/android/en-US/images/phoneScreenshots

workflows:
  deployment:
    jobs:
      - build-approval:
          type: approval
          filters:
            branches:
              only: master
      - android-deployment:
          requires:
            - build-approval
          context:
            - android-fastlane