version: 2.1

jobs:
  build:
    docker:
      - image: mobiledevops/flutter-sdk-image
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
      - run: flutter build apk --release
      - store_artifacts:
          path: /home/mobiledevops/project/build/app/outputs/flutter-apk/app-release.apk
          destination: artifact-file
